version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-load-balancer
    ports:
      - "8001:8001"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
